### ISSUE TITLE
Proposed additional packages

### ISSUE THREAD

**Issue by pdbailey0** [cran-task-views/Psychometrics#3]
I'm proposing this view would benefit from the inclusion of some packages that I maintain:

- [WeMix](https://cran.r-project.org/package=WeMix) fits n-level weighted linear mixed models and 2-level generalized linear models
- [Dire](https://cran.r-project.org/package=Dire) estimates latent regressions using direct estimation and can generate plausible values based on those latent regressions

**Comment by yrosseel** [comment]
I wonder if section 5.1 ( Analysis of Survey Data: Estimation and Variance Estimation) of the [OfficialStatistics & Survey Statistics](https://cran.r-project.org/web/views/OfficialStatistics.html) task view is not a better fit for the WeMix package? Otherwise, it could go to the 'Other Related Packages' of the psychometrics task view (unless you have a better suggestion)?

The Dire package could go in the ' Structural Equation Models (SEM)' section of the psychometrics task view. Agreed?

**Comment by pdbailey0** [comment]
@yrosseel thank you for the response and suggestions. I like both suggestions: 5.1 and SEM, which seem correct for WeMix and Dire, respectively. What do I next do?

**Comment by yrosseel** [comment]
For WeMix, you can open an issue on the [github site for the OfficialStatistics task view](https://github.com/cran-task-views/OfficialStatistics/issues).

For Dire, the easiest (for me) is that you add the description of 'Dire' yourself (using git) and create a pull request. I then just need to review it and accept if ok. Alternatively, you can type below the exact description of the package as you would like it to appear in the task view, and I will then add it myself (in a few days, once I am back in office).
